from dotenv import load_dotenv
import os

load_dotenv()

TOKEN = os.getenv("BOT_TOKEN")
BOT_USERNAME = "ootl_bot"

# Game Constants
MAX_PLAYERS = 10
MIN_PLAYERS = 3
NUM_WORD_CHOICES = 7
MAX_ROUNDS = 25
MIN_ROUNDS = 1
MIN_UNIQUE_WORDS = 13
MIN_LINES_FOR_CATEGORY = 14
POINTS_SMALL = 5
POINTS_STANDARD = 10
POINTS_LARGE = 20
GAME_ID_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
GAME_ID_LENGTH = 6

# UI Constants
CATEGORIES_PER_PAGE = 5
ROUND_ADJUST_STEPS = [1, 2, 5, 10]
SCORE_EDIT_STEPS = [2, 5]
PLAYER_COUNT_OPTIONS_PER_ROW = 2
ARROWS = {
  "up": "⬆️",
  "same": "➡️",
  "down": "⬇️",
}

#Telegram Specific Constants
RETRY_SLEEP_SECONDS = 1
TELEGRAM_MAX_TEXT_LENGTH = 4096
TELEGRAM_MAX_CAPTION_LENGTH = 1024
TELEGRAM_MAX_CALLBACK_DATA_BYTES = 64
TELEGRAM_LENGTH_WARNING_THRESHOLD = 0.9
